# MTK Interface (vendor)
PRODUCT_PACKAGES += \
    vendor.mediatek.hardware.apmonitor@2.0.vendor \
    vendor.mediatek.hardware.atci@1.0.vendor \
    vendor.mediatek.hardware.audio@6.1.vendor \
    vendor.mediatek.hardware.bluetooth.audio@2.1.vendor \
    vendor.mediatek.hardware.camera.advcam@1.0.vendor \
    vendor.mediatek.hardware.camera.atms@1.0.vendor \
    vendor.mediatek.hardware.camera.bgservice@1.1.vendor \
    vendor.mediatek.hardware.camera.callbackclient@1.2.vendor \
    vendor.mediatek.hardware.camera.camdump@1.0.vendor \
    vendor.mediatek.hardware.camera.ccap@1.0.vendor \
    vendor.mediatek.hardware.camera.device@1.2.vendor \
    vendor.mediatek.hardware.camera.frhandler@1.0.vendor \
    vendor.mediatek.hardware.camera.isphal@1.0.vendor \
    vendor.mediatek.hardware.camera.lomoeffect@1.0.vendor \
    vendor.mediatek.hardware.camera.security@1.0.vendor \
    vendor.mediatek.hardware.camera.vpuclient@2.0.vendor \
    vendor.mediatek.hardware.clientapi@1.0.vendor \
    vendor.mediatek.hardware.dfps@1.0.vendor \
    vendor.mediatek.hardware.dmc@1.1.vendor \
    vendor.mediatek.hardware.dplanner@2.0.vendor \
    vendor.mediatek.hardware.engineermode@1.3.vendor \
    vendor.mediatek.hardware.fm@1.0.vendor \
    vendor.mediatek.hardware.gnss@1.1.vendor \
    vendor.mediatek.hardware.gpu@1.0.vendor \
    vendor.mediatek.hardware.hdmi@1.1.vendor \
    vendor.mediatek.hardware.imsa@1.0.vendor \
    vendor.mediatek.hardware.keyinstall@1.0.vendor \
    vendor.mediatek.hardware.keymanage@1.0.vendor \
    vendor.mediatek.hardware.keymaster_attestation@1.1.vendor \
    vendor.mediatek.hardware.lbs@1.0.vendor \
    vendor.mediatek.hardware.log@1.0.vendor \
    vendor.mediatek.hardware.mdmonitor@1.0.vendor \
    vendor.mediatek.hardware.mms@1.5.vendor \
    vendor.mediatek.hardware.modemdbfilter@1.0.vendor \
    vendor.mediatek.hardware.mtkcodecservice@1.1.vendor \
    vendor.mediatek.hardware.mtkpower@1.0.vendor \
    vendor.mediatek.hardware.mtkradioex@2.0.vendor \
    vendor.mediatek.hardware.netdagent@1.0.vendor \
    vendor.mediatek.hardware.neuropilot@1.1.vendor \
    vendor.mediatek.hardware.nvram@1.1.vendor \
    vendor.mediatek.hardware.nwk_opt@1.0.vendor \
    vendor.mediatek.hardware.omadm@1.0.vendor \
    vendor.mediatek.hardware.power@2.1.vendor \
    vendor.mediatek.hardware.pplagent@1.0.vendor \
    vendor.mediatek.hardware.pq@2.6.vendor \
    vendor.mediatek.hardware.presence@1.0.vendor \
    vendor.mediatek.hardware.radio@3.9.vendor \
    vendor.mediatek.hardware.radio.deprecated@1.1.vendor \
    vendor.mediatek.hardware.radio_op@2.0.vendor \
    vendor.mediatek.hardware.rcs@2.0.vendor \
    vendor.mediatek.hardware.videotelephony@1.0.vendor \
    vendor.mediatek.hardware.wfo@1.0.vendor \
    vendor.mediatek.hardware.wifi.hostapd@2.0.vendor \
    vendor.mediatek.hardware.wifi.supplicant@2.2.vendor \
    vendor.mediatek.hardware.camera.postproc@1.0.vendor
